version: '3'

services:
  pywps:
    build: ./pywps
    container_name: pywps4geonode
    restart: always
    env_file: .imports_pywps_env
    volumes:
      - pywps_logs:/pywps-flask/logs
      - pywps_output:/pywps-flask/outputs
      - pywps_processes:/pywps-flask/processes
    networks:
      - backend

  mviewer:
    build: ./mviewer
    container_name: mviewer4geonode
    restart: always
    environment:
      - VIRTUAL_HOST=mviewer.geonode.local
      - VIRTUAL_PORT=80
    volumes:
      - mviewer:/usr/share/nginx/mviewer/
    networks:
      - backend
  
  tileserver:
    build: ./tileserver-gl
    container_name: tileserver4geonode
    restart: always
    expose:
      - "80"    
    environment:
      - VIRTUAL_HOST=tileserver.geonode.local
      - VIRTUAL_PORT=80
    volumes:
      - tiles-data:/data
    networks:
      - backend

networks:
  backend:   
    external:
      name: localinstall_backend

volumes:
  tiles-data:
  mviewer:
  pywps_logs:
  pywps_output:
  pywps_processes:
