version: '3'

services:
  web:
    build: ./mviewer
    container_name: mviewer4geonode
    restart: always
    # Modify the following parameters like this :
    #    - VIRTUAL_HOST -> the service domain name
    #    - VIRTUAL_PORT -> 80
    environment:
      - VIRTUAL_HOST=mviewer.geonode.local
      - VIRTUAL_PORT=80
    networks:
      - geonode
      - backend

networks:
  geonode:
    external:
      #Replace here the backend network name obtained from sudo docker network ls
      name: geonode_geonode
  backend: