version: '3'

services:
  pywps:
    build: ./pywps
    container_name: pywps4geonode
    restart: always
    # Modify the following parameters like this :
    #    - VIRTUAL_HOST -> the service domain name
    #    - VIRTUAL_PORT -> 80
    environment:
      - VIRTUAL_HOST=compute.geonode.local
      - VIRTUAL_PORT=5000
    networks:
      - geonode
      - backend

networks:
  geonode:
    external:
      #Replace here the backend network name obtained from sudo docker network ls
      name: geonode_geonode
  backend: