version: '3'

services:
  proxy:
    build: ./proxy
    restart: always
    container_name: proxy4spgeo22
    ports:
      - 80:80
    volumes:
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - backend

  portainer:
    image: portainer/portainer:latest
    container_name: portainer4spgeo22
    environment:
      - VIRTUAL_HOST=portainer.geonode.local
      - VIRTUAL_PORT=80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    networks:
      - backend

volumes:
  vhost.d:
  html:

networks:
  backend:
